"""revised some tables

Revision ID: ec359d4ed902
Revises: cf1d6d25093c
Create Date: 2022-05-25 14:42:20.323610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec359d4ed902'
down_revision = 'cf1d6d25093c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
    op.drop_constraint('projects_name_key', 'projects', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('projects_name_key', 'projects', ['name'])
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)
    # ### end Alembic commands ###
