"""empty message

Revision ID: 15afec9e6611
Revises: cd03dfd4429e
Create Date: 2022-05-27 14:30:54.404558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15afec9e6611'
down_revision = 'cd03dfd4429e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_private', sa.Boolean(), nullable=False))
    op.drop_column('projects', 'is_public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('projects', 'is_private')
    # ### end Alembic commands ###
