"""revise tables

Revision ID: b44de681e307
Revises: 61c523ed6e95
Create Date: 2022-05-25 13:48:10.807337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b44de681e307'
down_revision = '61c523ed6e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_completed', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('priority_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'priorities', ['priority_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'priority_id')
    op.drop_column('tasks', 'is_completed')
    # ### end Alembic commands ###
